#!/bin/bash
#
# SLASS - seelenlos Arma3 Server Script
# 
# Author: joka
# 
# Description:
# manages Arma3 servers
# 
# Parameter(s):
# 1. option { start | stop | install | update | wsupdate} <string>
# 2. server id {i} <integer>
# 
# Return Value:
# None <Any>
#
# enable debugging if needed
debug=""
debug="y"
#
# enable REALLY verbose debugging if needed
verbose="n"
if [[ $verbose == "y" ]] ; then
	export PS4="\$LINENO: "
	set -xv
fi
#
# detect path to slass
basepath=$(dirname "$(readlink -f "$0")")
#
# load function
source $basepath/slass-data/module/m_fnloader.sh
#
fn_debugMessage " slass: Path to slass: $basepath"
#
#
opt1="$1"
serverid="$2"
#
#
case "$opt1" in
#
#
start|stop|restart|status|log)
#
# test input variable { i }
re='^[0-9]+$'
if ! [[ $serverid =~ $re ]] ; then
	fn_printMessage "wrong argument 2" ""
	fn_printMessage "expected arguments ( integer number )" ""
	exit 1
fi
#
fn_printMessage "$opt1 of Server $serverid ..." ""
source $basepath/slass-data/module/m_a3server.sh $opt1 $serverid
;;
#
#
stopall)
fn_printMessage "stoppping all servers" ""
fn_stopall $basepath
;;
#
#
install)

;;
#
#
update)

;;
#
#
wsupdate)

;;
#
#
*)
	fn_printMessage " wrong argument 1" ""
	fn_printMessage " expected arguments ( start | stop | install | update | wsupdate)" ""
	exit 1
;;

esac